export const GITHUB_USERS_FIELD_AUTOSUGGEST_REQUEST = 'GITHUB_USERS_FIELD_AUTOSUGGEST_REQUEST';
export const GITHUB_USERS_FIELD_AUTOSUGGEST_SUCCESS = 'GITHUB_USERS_FIELD_AUTOSUGGEST_SUCCESS';
export const GITHUB_USERS_FIELD_AUTOSUGGEST_FAILURE = 'GITHUB_USERS_FIELD_AUTOSUGGEST_FAILURE';

export function AutoSuggestRequestAction(field) {
  return { type: GITHUB_USERS_FIELD_AUTOSUGGEST_REQUEST, field };
}
