export const GITHUB_USERS_USER_DETAIL_FORM_REQUEST = 'GITHUB_USERS_USER_DETAIL_FORM_REQUEST';
export const GITHUB_USERS_USER_DETAIL_FORM_SUCCESS = 'GITHUB_USERS_USER_DETAIL_FORM_SUCCESS';
export const GITHUB_USERS_USER_DETAIL_FORM_FAILURE = 'GITHUB_USERS_USER_DETAIL_FORM_FAILURE';

export const GITHUB_USERS_USER_DETAIL_EXTRA_INFO_FORM_REQUEST = 'GITHUB_USERS_USER_DETAIL_EXTRA_INFO_FORM_REQUEST';
export const GITHUB_USERS_USER_DETAIL_EXTRA_INFO_FORM_SUCCESS = 'GITHUB_USERS_USER_DETAIL_EXTRA_INFO_FORM_SUCCESS';
export const GITHUB_USERS_USER_DETAIL_EXTRA_INFO_FORM_FAILURE = 'GITHUB_USERS_USER_DETAIL_EXTRA_INFO_FORM_FAILURE';

export function UserDetailRequestAction(userLogin) {
  return { type: GITHUB_USERS_USER_DETAIL_FORM_REQUEST, userLogin };
}

export function UserDetailExtraInfoRequestAction(param) {
  return { type: GITHUB_USERS_USER_DETAIL_EXTRA_INFO_FORM_REQUEST, param };
}
