export const GITHUB_USERS_USER_FORM_REQUEST = 'GITHUB_USERS_USER_FORM_REQUEST';
export const GITHUB_USERS_USER_FORM_SUCCESS = 'GITHUB_USERS_USER_FORM_SUCCESS';
export const GITHUB_USERS_USER_FORM_FAILURE = 'GITHUB_USERS_USER_FORM_FAILURE';

export function UserDetailRequestAction(userLogin) {
  return { type: GITHUB_USERS_USER_FORM_REQUEST, userLogin };
}
